nodeLinker: node-modules

npmScopes:
  mause:
    npmAlwaysAuth: true
    npmRegistryServer: "https://npm.pkg.github.com"
    npmPublishRegistry: "https://npm.pkg.github.com"

npmRegistries:
  "https://npm.pkg.github.com":
    npmAlwaysAuth: true
